name: clean_base
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  path_provider: ^2.0.11
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  persian_datetime_picker: ^2.5.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.4
  flutter_advanced_networkimage_2: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: IranSansFA
      fonts:
        - asset: assets/fonts/iransans/fa-iransans-regular.ttf
        - asset: assets/fonts/iransans/fa-iransans-bold.ttf
        - asset: assets/fonts/iransans/fa-iransans-black.ttf
        - asset: assets/fonts/iransans/fa-iransans-medium.ttf
